export const universityName = [
  "",
  "Ajou University",
  "Chungang University",
  "Daejin University",
  "Dong-a University",
  "Dong-Eui University",
  "Ewha Womans University",
  "Gwangju Institute of Science and Technology",
  "Hankuk University of Foreign Studies",
  "Hanyang University",
  "Hongik University",
  "Inha University",
  "Kookmin University",
  "Korea Advanced Institute of Science & Technology",
  "Korea University Seoul Campus",
  "Kyungpook National University",
  "Myongji University",
  "Pukyong National University Daeyeon Campus",
  "Sahmyook University",
  "Sangmyung University",
  "Seoul National University of Science and Technology",
  "Seoul Women's University",
  "Sookmyung Women's University",
  "Soonchunhyang University",
  "Soongsil University",
  "Sungkonghoe University",
  "Sungkyunkwan University",
  "Sungshin Women's University",
  "Tech University of Korea",
  "University of Seoul",
  "Yonsei University Mirae Campus",
  "Yonsei University Seoul Campus",
];
